apiVersion: v1
kind: Deployment
metadata:
  name: backend
  namespace: ay262-parker-namespace
spec:
  replicas: 1
  selector:
    matchlabels:
      app: backend
  template:
    metadata:
      labels:
        app:
          backend
    spec:
      containers:
      - name: backend
        image: seat-scout-backend
        ports:
        - contianerPort: 5000