apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ay262-parker-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app:
          backend
    spec:
      containers:
      - name: backend
        image: trying72/seat-scout-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DB
          value: phase2-mysql-database
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
