apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ay262-parker-namespace
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 10.43.50.241
  type: ClusterIP